# 정렬
- 배열 값을 기준에 따라 순서대로 배치하는 작업임
- 오름차순/내림차순 정렬 가능함
- 원본 유지 여부 확인 필요함


In [1]:
import numpy as np

# - 원본 배열은 유지
# - 원본 데이터 유지 여부는 데이터 전처리에 있어서 중요한 부분이다.
arr = np.random.randint(1, 11, 10)
print("arr: ", arr)

print("np.sort(arr): ", np.sort(arr)) # 정렬
print("arr: ", arr) # 원본 유지 확인

arr:  [1 1 7 4 6 4 7 8 3 9]
np.sort(arr):  [1 1 3 4 4 6 7 7 8 9]
arr:  [1 1 7 4 6 4 7 8 3 9]


In [2]:
# 내림 차순(역순 정렬) -> 슬라이싱 방식 이용
np.sort(arr)[::-1]

array([9, 8, 7, 7, 6, 4, 4, 3, 1, 1], dtype=int32)

In [6]:
# 2차원 배열 형태의 데이터 정렬
# - axis에 따라 정렬 기준이 달라짐
# - axis = None - 전체 (1차원으로 변경 후 전체 정렬)
# - axis = 0 - 각 행 안에서 열 데이터를 정렬
# - axis = 1 - 각 열 안에서 행 데이터를 정렬

np.random.seed(34)
arr = np.random.randint(1, 15, (3, 4))
print(arr)

print("np.sort(arr, axis=None)")
print(np.sort(arr, axis=None))

print("np.sort(arr, axis=0)")
print(np.sort(arr, axis=0))

print("np.sort(arr, axis=1)")
print(np.sort(arr, axis=1))

[[ 2 11 11 10]
 [ 7  6  5  4]
 [ 6 12 11 14]]
np.sort(arr, axis=None)
[ 2  4  5  6  6  7 10 11 11 11 12 14]
np.sort(arr, axis=0)
[[ 2  6  5  4]
 [ 6 11 11 10]
 [ 7 12 11 14]]
np.sort(arr, axis=1)
[[ 2 10 11 11]
 [ 4  5  6  7]
 [ 6 11 12 14]]


## np.argsort()
- 배열 요소를 정렬했을 때의 인덱스를 반환함
- 정렬된 값 자체가 아니라 정렬 순서임
- 실제 정렬값은 `arr[indices]`처럼 다시 인덱싱해야 함


In [9]:
# argsort()의 결과값은 정렬 순서를 만드는 인덱스다

arr = np.array([40, 10, 20, 30])
indices = np.argsort(-arr) # arr * -1
print(indices)
print(arr[indices])

[0 3 2 1]
[40 30 20 10]


In [12]:
# 2차원 argsort(axis = 0)
arr = np.array([[30, 10, 20], [60, 40, 50]])

indices = np.argsort(arr, axis=1)
print(indices)
# print(arr[indices])

[[1 2 0]
 [1 2 0]]


In [19]:
# 각 배열의 같은 인덱스 요소가 한 학생의 이름, 점수를 나타내고 있음
# 학생의 이름으로 점수 내림차순 순서로 정렬
names = np.array(['홍길동', '신사임당', '이순신', '유관순'])
scores = np.array([90, 30, 50, 70])
sorted_score = np.argsort(-scores)
print(names[sorted_score])

['홍길동' '유관순' '이순신' '신사임당']


In [23]:
# 우선순위에 따른 작업 정렬(작은 수일수록 높은 우선 순위)
priorities = np.array([3, 1, 2, 5, 4])
tasks = np.array(["Task A", "Task B", "Task C", "Task D", "Task E"])

sorted_priorities = np.argsort(priorities)
# print(sorted_priorities)
print(tasks[sorted_priorities])
# 결과: ["Task B" "Task C" "Task A" "Task E" "Task D"]

['Task B' 'Task C' 'Task A' 'Task E' 'Task D']
