# [7] Numpy 종합 실습

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

- **데이터 (**각 지점의 월별 과일 판매량(단위: 개))

    ```python
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])
    ```

In [5]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

# 인덱싱을 위한 라벨 배열 (월 데이터도 배열로 만듭니다)
fruits = np.array(['사과', '바나나', '오렌지'])
branches = np.array(['지점 1', '지점 2', '지점 3', '지점 4', '지점 5'])
months = np.array(['1월', '2월', '3월', '4월', '5월', '6월'])

print("========== [문제 1: 지점별 과일 월평균] ==========")
# 소수점 1자리까지 반올림
avg_sales = np.round(np.mean(sales_data, axis=2), 1)
# 지점 배열과 평균 배열을 가로로 결합 (column_stack)
result_1 = np.column_stack((branches, avg_sales))
print("[지점명, 사과, 바나나, 오렌지]")
print(result_1)


print("\n========== [문제 2: 월별 1등 과일] ==========")
monthly_total = np.sum(sales_data, axis=0)
max_idx = np.argmax(monthly_total, axis=0)
max_val = np.max(monthly_total, axis=0)
# 월, 1등과일, 판매량을 가로로 묶어서 한 번에 출력
result_2 = np.column_stack((months, fruits[max_idx], max_val))
print("[월, 과일명, 판매량]")
print(result_2)


print("\n========== [문제 3: 전체 누적 판매량] ==========")
total_sales = np.sum(sales_data, axis=(0, 2))
# 과일과 총판매량을 가로로 결합
result_3 = np.column_stack((fruits, total_sales))
print("[과일명, 총판매량]")
print(result_3)
print(f"👉 전체 1등 과일: {fruits[np.argmax(total_sales)]}")


print("\n========== [문제 4: 150개 이상 판매 기록] ==========")
# np.where로 조건에 맞는 튜플 반환 (지점_idx, 과일_idx, 월_idx)
b_idx, f_idx, m_idx = np.where(sales_data >= 150)
# 팬시 인덱싱으로 라벨을 한 번에 뽑아내고, 판매량 데이터도 한 번에 추출하여 결합
result_4 = np.column_stack((branches[b_idx], months[m_idx], fruits[f_idx], sales_data[sales_data >= 150]))
print("[지점, 월, 과일명, 판매량]")
print(result_4)


[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]
========== [문제 1: 지점별 과일 월평균] ==========
[지점명, 사과, 바나나, 오렌지]
[['지점 1' '181.7' '156.7' '131.7']
 ['지점 2' '111.7' '87.5' '85.8']
 ['지점 3' '161.7' '135.0' '120.0']
 ['지점 4' '148.3' '112.5' '115.0']
 ['지점 5' '120.0' '94.2' '90.8']]

========== [문제 2: 월별 1등 과일] ==========
[월, 과일명, 판매량]
[['1월' '사과' '520']
 ['2월' '사과' '620']
 ['3월' '사과' '750']
 ['4월' '사과' '860']
 ['5월' '사과' '760']
 ['6월' '사과' '830']]

========== [문제 3: 전체 누적 판매량] ==========
[과일명, 총판매량]
[['사과' '4340']
 ['바나나' '3515']
 ['오렌지' '3260']]
👉 전체 1등 과일: 사과

========== [문제 4: 150개 이상 판매 기록] ==========
[지점, 월, 과일명, 판매량]
[['지점 1' '2월' '사과' '150']
 ['지점 1' '3월' '사과' '200']
 ['지점 1' '4월' '사과' '230']
 ['지점 1' '5월' '사과' '180']
 ['지점 1' '6월' '사과' '210']
 ['지점 1' '3월' '바나나' '170']
 ['지점 1' '4월' '바나나' '190']
 ['지점 1' '5월' '바나나' '160']
 [

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.